version: '3.8'
services:
    test_db:
        container_name: crimlog_test_db
        image: mongo:6
        ports:
            - 27017:27017
        volumes:
            - ./test/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: test
        tmpfs: /data/db
