name: Code Functionality
on:
    pull_request:
        branches: [dev]

jobs:
    integration-test:
        name: Integration Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest

            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Run Integration Tests
              env:
                  NODE_OPTIONS: '--max_old_space_size=4096' # prevent out of memory errors (https://github.com/actions/runner-images/issues/70#issuecomment-1191708172)
              run: pnpm test:e2e --maxWorkers=2 # maxWorkers speed up tests (https://www.bharathvaj.me/blog/speedup-jest-github-actions)
